# Generated by Django 2.2.2 on 2019-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepost',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
