# Generated by Django 2.2.2 on 2019-06-27 01:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_basepost_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepost',
            name='vote_users',
            field=jsonfield.fields.JSONField(default={'vote_users': []}),
        ),
    ]
