# Generated by Django 2.2.2 on 2019-06-18 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BasePost')),
                ('title', models.CharField(max_length=2048)),
                ('feature_image', models.CharField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('Private draft', -1), ('Unlisted', 0), ('Public', 1)], default=('Private draft', -1), max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=2048)),
                ('views', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clips', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            bases=('base.basepost',),
        ),
    ]
