# Generated by Django 2.2.2 on 2019-06-27 00:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_views_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_id',
        ),
        migrations.AddField(
            model_name='post',
            name='views_id',
            field=jsonfield.fields.JSONField(default={'view_users': []}),
        ),
    ]
